### ISSUE TITLE
Is this only for Play 2.1?

### ISSUE THREAD

**Issue by benmccann** [scala-ide/scala-ide-play2#243]
Does this work with Play 2.3? The README says Play 2.1 in huge letters

**Comment by benmccann** [comment]
ping

**Comment by benmccann** [comment]
@dragos would you be able to take a quick look at this one?  it's been very confusing to me

**Comment by benmccann** [comment]
@dragos @huitseeker @skyluc can you take a quick look at this? thanks!

**Comment by benmccann** [comment]
@dragos is there someone from virtus labs we can ping to take a look at this?

**Comment by sschaef** [comment]
Did you try to work with Play 2.3? Did it work? Just because the doc says its for Play 2.1 it doesn't mean that it is not forward compatible.

**Comment by benmccann** [comment]
Is this supposed to work with Play 2.3? I could try it to find out if it works, but that seems like really something so basic that it should be in the docs. We could update them to say Play 2, or Play 2.x, or Play 2.1+

**Comment by dotta** [comment]
The latest release definitely works with Play 2.3.x. Older versions of Play 2 should also work (though, there is possibly some functionality that doesn't make sense. E.g., support for [injected controllers](https://www.playframework.com/documentation/2.3.x/ScalaDependencyInjection#Controller-Injection) in routes).

Both the README and wiki should be updated. If none beats me, I'll try to do it in the next few days.

**Comment by dotta** [comment]
I've updated both the README and the [wiki](https://github.com/scala-ide/scala-ide-play2/wiki)

**Comment by benmccann** [comment]
Thanks @dotta!
