### ISSUE TITLE
Tests using Guice won't inject dependencies when running out of IDE

### ISSUE THREAD

**Issue by ITler** [scala-ide/scala-ide-play2#261]
Hello guys,

I find this a hard nut to crack, so hopefully this is the right place for requesting assistance and one of you could help me out.
My issue is originally described on [stackoverflow](http://stackoverflow.com/questions/34827227/testing-playframework-2-4-with-spring-data-injection-out-of-eclipse-scala-ide). Could be worth reading for additional infos. I'm using

* play framework 2.4.6
* scala current 2.11.6 / sbt 0.13.8
* JAVA 8
* Spring data
* Eclipse Mars IDE with Scala IDE (downloaded and installed today)

I'd like to use Guice to inject Spring data repository to my Unit Tests. When doing this plain with `activator test` everything works fine. Doing this out of Eclipse, after using `activator eclipse` on my project, injection doesn't work. I recognized difference in classpath and wonder if that is the reason (although `core/bin` does contain all compiled `.class` including the Guice stuff).

    # Classpath output was sorted before
    $ diff activatorCP eclipseCP
    0a1
    > 
    88,89d88
    < /h/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.6.jar
    < /h/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.6.jar
    130,136c129,131
    < /h/.sbt/boot/scala-2.10.5/org.scala-sbt/sbt/0.13.9/test-agent-0.13.9.jar
    < /h/.sbt/boot/scala-2.10.5/org.scala-sbt/sbt/0.13.9/test-interface-1.0.jar
    < /h/workspace/springtest/core/target/scala-2.11/classes/
    < /h/workspace/springtest/core/target/scala-2.11/test-classes/
    < /h/workspace/springtest/core/target/web/classes/main/
    < /h/workspace/springtest/core/target/web/classes/test
    < /h/workspace/springtest/core/target/web/public/test/
    ---
    > /h/workspace/springtest/core/bin/
    > /opt/eclipse-mars/configuration/org.eclipse.osgi/213/0/.cp/
    > /opt/eclipse-mars/configuration/org.eclipse.osgi/214/0/.cp/

Is it correct, that classpath differs? Do you have an idea, what is wrong with my test setup and why it is not working as expected?

Thank you

**Comment by wpopielarski** [comment]
@ITler would be nice if you could add minimal version of your project to look into it

Cheers

**Comment by ITler** [comment]
@wpopielarski of cause. Please have a look [here](https://github.com/ITler/springtest). The sub-project `core` even runs.

**Comment by sschaef** [comment]
I get the following exception once I run the test in Eclipse:

```
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for models.PersonRepository was bound.
  while locating models.PersonRepository
    for field at core.ApplicationTest.repo(ApplicationTest.java:26)
  while locating core.ApplicationTest

...
```

This doesn't look an error in the IDE. Your configuration seems to be broken but I can't help because I have no idea how Guice resolves dependencies. How is it supposed to work? Shouldn't you have an implementation for the interface `PersonRepository`? I can't find one.

**Comment by ITler** [comment]
@sschaef Yeah, that's what I say in the linked stackoverflow post - and this is the problem I have.  
The `PersonRepository` implementation is *magically handled* by spring data, if Guice would manage to bootstrap the spring data context when running tests out of Eclipse. If you would run the tests out of [activator](https://playframework.com/download) using `activator test`, they will pass.
Maybe, this is not really an issue from the IDE, but it does only occur when using the IDE, so that's why I try to get help here. Maybe I should ask for help at playframework.

**Comment by sschaef** [comment]
On 01/31/2016 03:47 PM, ITler wrote:
>
> Maybe I should ask for help at playframework.
>
Please do that. They can tell you how it is supposed to work and they 
may also have an idea why it doesn't work from inside of the IDE.

**Comment by wpopielarski** [comment]
funny thing, I just found that renaming core-application.conf to application.conf solves problem with ApplicationTest

**Comment by wpopielarski** [comment]
Hey my young friend (btw I'm pretty old guy :) ), looks like in 'Run as' configuration you need to add `-Dconfig.resource=core-application.conf` in Arguments tab. I see this is added to javaopts in build.sbt too and it would explain why activator is ok with it.

**Comment by ITler** [comment]
I'll look at this as soon as I can.

**Comment by ITler** [comment]
Can't believe it. It's too simple. I didn't take this into consideration. Somehow I have expected that some magic would happen when using `activator eclipse` taking care of eclipse configuration... Again, I've learned something, that's why I'm doing all of this. 
Thanks to my pretty old friend :)

**Comment by ITler** [comment]
@wpopielarski if you give this answer on [stackoverflow](http://stackoverflow.com/questions/34827227/testing-playframework-2-4-with-spring-data-injection-out-of-eclipse-scala-ide), I could vote you up there.

**Comment by wpopielarski** [comment]
unfortunately I don't have stackoverflow account, I'm a little bit like
software Amish ;-), but if you think there is more such requests feel free
to publish it there with your own name.

2016-02-05 13:51 GMT+01:00 ITler <notifications@github.com>:
