### ISSUE TITLE
Unit file re-compilation not happening after persisted syntax error

### ISSUE THREAD

**Issue by ITler** [scala-ide/scala-ide-play2#264]
Hello,

I'm facing a real annoying problem when working with my Scala IDE on [this][1] project.

#### Environment information
* Ubuntu 14 LTS 64bit (unity desktop)
* Scala: 2.11.6 (also applies to 2.11.7)
* Sbt: 0.3.18
* Java: Oracle 1.8.0_25
* IDE: 
    *  Eclipse Mars.1 standard (official download) with 
    *  current Scala IDE plugins (4.3) and all plugins from update site.
    *  `-Xss8M`, `-Xms640m`, `-Xmx2048m`

#### IDE setup
IDE's java compiler and scala compiler are set to use java 1.8 for compilation. The scala compiler uses dynamically bundled 2.11 installation.
The project and its sub-project gets exported to eclipse the default way (`activator eclipse`). No more modifications took place.

#### Approaching the problem
Importing the project in Eclipse IDE, initially, works fine (no compilation errors). I'm able to execute JUnit tests via IDE. The IDE is set up with `Build Automatically` to auto-build code changes. 
Now, when editing JUnit tests and saving the file containing syntax errors (how provoking), IDE indicating the issue
* in the editor window by underlining the incorrect code in red color and
* with the little red icon overlay on the file in package explorer.

Works as it should.

#### Facing the problem
After fixing the syntax error in JUnit file, I'll save the file again, but
* the little red icon overlay on the file in package explorer does not disappear and
* the red underline in code gets removed *only sometimes but not always*.

**Note:** this applies for JUnit files, not for 'regular' code files.

#### Work-around
My only chance is to manually `Clean...` the project to get a new compiled JUnit file for testing. Extremely annoying - no fun here.

#### Tracking the issue
I've tried to reproduce the issue with a default plain and simple java project, which contains one java source file and one junit file. This works perfect, generally.

Back to my play-project: I've closed eclipse and deleted log files `scala-ide.log` and `.metadata/.log`. I've restarted eclipse, reproduced the problem and checked log files again. IMO, Log does not indicate any problem referring the issue.

    # .metadata/.log
    
    !SESSION 2016-02-19 16:23:38.775 -----------------------------------------------
    eclipse.buildId=4.5.1.M20150904-0015
    java.version=1.8.0_25
    java.vendor=Oracle Corporation
    BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
    Framework arguments:  -product org.eclipse.epp.package.java.product
    Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product
    
    # Here are some key binding issues indicating duplicate shortcuts. Should not be relevant, omitted.
    
    !ENTRY org.scala-ide.sdt.core 2 0 2016-02-19 16:24:09.444
    !MESSAGE Preference scala.compiler.sourceLevel was uninitialized for frontend, setting default to 2.11.
    
    !ENTRY org.scala-ide.sdt.core 2 0 2016-02-19 16:24:09.450
    !MESSAGE Preference scala.compiler.installation was uninitialized for frontend, setting default to 2.11.

and

    # scala-ide.log
    
    2016-02-19 16:24:00,553 ERROR [main] - System.err - [org.eclipse.jdt.launching] error can't determine modifiers of missing type org.eclipse.pde.internal.ui.wizards.imports.PluginImportHelper
    when weaving type org.eclipse.jdt.launching.JavaRuntime
    when weaving classes 
    when weaving 
     [Xlint:cantFindType]
    2016-02-19 16:24:00,650 ERROR [main] - System.err - [org.eclipse.debug.core] error can't determine modifiers of missing type org.eclipse.pde.internal.ui.wizards.imports.PluginImportHelper
    when weaving type org.eclipse.debug.core.ILaunchesListener
    when weaving classes 
    when weaving 
     [Xlint:cantFindType]
    2016-02-19 16:24:04,450 ERROR [main] - System.err - [org.eclipse.jdt.junit] error can't determine modifiers of missing type org.eclipse.pde.internal.ui.wizards.imports.PluginImportHelper
    when weaving type org.eclipse.jdt.internal.junit.ui.TestRunnerViewPart
    when weaving classes 
    when weaving 
     [Xlint:cantFindType]
    2016-02-19 16:24:09,445  WARN [main] - org.scala-ide.sdt.core - org.scala-ide.sdt.core - org.scala-ide.sdt.core - 0 - Preference scala.compiler.sourceLevel was uninitialized for frontend, setting default to 2.11.
    2016-02-19 16:24:09,450  WARN [main] - org.scala-ide.sdt.core - org.scala-ide.sdt.core - org.scala-ide.sdt.core - 0 - Preference scala.compiler.installation was uninitialized for frontend, setting default to 2.11.
    2016-02-19 16:24:10,608 ERROR [main] - System.err - [org.eclipse.jdt.debug.ui] error can't determine modifiers of missing type org.eclipse.pde.internal.ui.wizards.imports.PluginImportHelper
    when weaving type org.eclipse.jdt.internal.debug.ui.actions.RetargettableActionAdapterFactory
    when weaving classes 
    when weaving 
     [Xlint:cantFindType]
    2016-02-19 16:24:10,718 ERROR [main] - System.err - [org.eclipse.jdt.debug] error can't determine modifiers of missing type org.eclipse.pde.internal.ui.wizards.imports.PluginImportHelper
    when weaving type org.eclipse.jdt.debug.core.IJavaHotCodeReplaceListener
    when weaving classes 
    when weaving 
     [Xlint:cantFindType]

This doesn't help me, so I ask you for help. 

Thanks!
ITler

  [1]: https://github.com/ITler/springtest

**Comment by ITler** [comment]
I've found a setting which I've had to disable to get rid of this behavior: `stopBuildOnError` in Scala Compiler options

**Comment by sschaef** [comment]
What most people do is they disable build automatically and let the sbt build the project with a `~compile`. That is still not perfect because the IDE doesn't get notified about all build changes but until we have full sbt support in the IDE it is probably the best solution.

**Comment by ITler** [comment]
@sschaef Thanks for replying. What would be your estimation, when full sbt support would be achieved? Do you mean weeks or months?
Best regards
ITler

**Comment by sschaef** [comment]
The plan is to get it up and running within the next 3 months.

**Comment by ITler** [comment]
Thanks for information
