### ISSUE TITLE
Updatesite is not availiable: Scala IDE Play2 Plugin (4.x), Nightly 

### ISSUE THREAD

**Issue by thrxde** [scala-ide/scala-ide-play2#267]
Updatesite is not availiable:
http://download.scala-ide.org/play2/2.11.x/nightly-scala-ide-nightly-e44/site/

jenkins output of build job:

https://jenkins.scala-ide.org:8496/jenkins/job/play2-nightly-scala-ide-2.11-e44/
```
[INFO] ------------------------------------------------------------------------
+ ssh scalaide@scala-ide.dreamhosters.com mkdir -p scala-ide.dreamhosters.com/play2/2.11.x/nightly-scala-ide-nightly-e44
ssh: Could not resolve hostname scala-ide.dreamhosters.com: Name or service not known
Build step 'Execute shell' marked build as failure
Recording test results
Finished: FAILURE
```

**Comment by sschaef** [comment]
where did you find that link?

**Comment by sschaef** [comment]
Ok, I guess you found it on the wiki. We no longer publish nightlies for the Play IDE. I removed the section about the nightlies.

**Comment by sschaef** [comment]
Actually, we can bring the nightlies back to live. I fixed the nightly build already. It publishes the update site at https://jenkins.scala-ide.org:8496/jenkins/job/play2-nightly-scala-ide-2.11-e44/lastSuccessfulBuild/artifact/play2/org.scala-ide.play2.update-site/target/site/. @dragos Would you please add an redirect to the update site to make the URL simpler?

**Comment by thrxde** [comment]
@sschaef Thanks for the fast investigation, the update-site works. 
@dragos Maybe it is possibel to use the old link for the redirect?

**Comment by dragos** [comment]
Sorry, missed this one. I'll add a redirect from the old url

**Comment by dragos** [comment]
BTW, it looks like the nightly is older than the release version, so it can't be installed over it...

**Comment by dragos** [comment]
Done!

**Comment by sschaef** [comment]
Installing the nighty should work, it is 0.8.0-SNAPSHOT, the release is 0.7.0.

**Comment by thrxde** [comment]
@sschaef  an new version is not built, because build error. I opened an new issue #269 where you can find the details.
