### ISSUE TITLE
nightly build failed since "scala-ide/plugin-profiles" update to version 1.0.12

### ISSUE THREAD

**Issue by thrxde** [scala-ide/scala-ide-play2#269]
Error: 

Failed to load p2 repository with ID 'scala-ide' from location http://download.scala-ide.org/nightly-scala-ide-mars-211x

[Jenkins error Log](https://jenkins.scala-ide.org:8496/jenkins/job/play2-nightly-scala-ide-2.11-e44/462/console)

It was caused by following changes: 
[scala-ide-play2 commit](https://github.com/scala-ide/scala-ide-play2/commit/8fec446bf2bf5262e3d9217ec69552bf86d7fc6e#diff-600376dffeb79835ede4a0b285078036)
[scala-ide plugin-profiles](https://github.com/scala-ide/plugin-profiles/commit/62dbf1d741b39b304a57125bdc0fb34dee5003fb?diff=unified)

which buids the repo url in the following way:
``` xml
<profile>
      <id>scala-ide-nightly</id> <!-- Update site for Scala IDE Nighlties -->
      <properties>
         <repo.scala-ide>${repo.scala-ide.root}/nightly-scala-ide-${scala-ide-branch}-${ecosystem-scala-version}x</repo.scala-ide>
      </properties>
    </profile>
```

**Comment by sschaef** [comment]
@dragos @skyluc Would one of you please add a redirect from `http://download.scala-ide.org/nightly-scala-ide-mars-211x` to `https://jenkins.scala-ide.org:8496/jenkins/view/Parameterized%20Nightly%20Jobs/job/parameterized-scala-ide-mars/lastSuccessfulBuild/artifact/scala-ide/org.scala-ide.sdt.update-site/target/site/`. That should fix this issue.

**Comment by cunei** [comment]
The redirect is in place

**Comment by sschaef** [comment]
Thanks!

**Comment by thrxde** [comment]
Subfolders needs redirect too, because http://download.scala-ide.org/nightly-scala-ide-mars-211x/plugins/ causes AccessDenied

**Comment by sschaef** [comment]
There are two subfolders: `plugins` and `features`

**Comment by thrxde** [comment]
Yes, please redirect 
from `http://download.scala-ide.org/nightly-scala-ide-mars-211x/plugins` 
to `https://jenkins.scala-ide.org:8496/jenkins/view/Parameterized%20Nightly%20Jobs/job/parameterized-scala-ide-mars/lastSuccessfulBuild/artifact/scala-ide/org.scala-ide.sdt.update-site/target/site/plugins/` 
and `http://download.scala-ide.org/nightly-scala-ide-mars-211x/features`
to `https://jenkins.scala-ide.org:8496/jenkins/view/Parameterized%20Nightly%20Jobs/job/parameterized-scala-ide-mars/lastSuccessfulBuild/artifact/scala-ide/org.scala-ide.sdt.update-site/target/site/features/`

**Comment by cunei** [comment]
A previous redirection rule was kicking in. I slightly changed the target to remove the view component. Should be ok now.

**Comment by sschaef** [comment]
Yes, seems to work fine. Thanks @cunei.

**Comment by thrxde** [comment]
Eclipse update works ... Thanks
